# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: products.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
		_runtime_version.Domain.PUBLIC,
		6,
		31,
		1,
		'',
		'products.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproducts.proto\x12\x08products"\x1c\n\x0eProductRequest\x12\n\n\x02id\x18\x01 \x01(\x05"[\n\x0cProductReply\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\x12\r\n\x05stock\x18\x05 \x01(\x05"2\n\x13ListProductsRequest\x12\x0c\n\x04skip\x18\x01 \x01(\x05\x12\r\n\x05limit\x18\x02 \x01(\x05"=\n\x11ListProductsReply\x12(\n\x08products\x18\x01 \x03(\x0b\x32\x16.products.ProductReply2\x96\x01\n\x08Products\x12>\n\nGetProduct\x12\x18.products.ProductRequest\x1a\x16.products.ProductReply\x12J\n\x0cListProducts\x12\x1d.products.ListProductsRequest\x1a\x1b.products.ListProductsReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'products_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
	DESCRIPTOR._loaded_options = None
	_globals['_PRODUCTREQUEST']._serialized_start=28
	_globals['_PRODUCTREQUEST']._serialized_end=56
	_globals['_PRODUCTREPLY']._serialized_start=58
	_globals['_PRODUCTREPLY']._serialized_end=149
	_globals['_LISTPRODUCTSREQUEST']._serialized_start=151
	_globals['_LISTPRODUCTSREQUEST']._serialized_end=201
	_globals['_LISTPRODUCTSREPLY']._serialized_start=203
	_globals['_LISTPRODUCTSREPLY']._serialized_end=264
	_globals['_PRODUCTS']._serialized_start=267
	_globals['_PRODUCTS']._serialized_end=417
# @@protoc_insertion_point(module_scope)
